### ISSUE TITLE
Indent wrong

### ISSUE THREAD

**Issue by luoyanghero** [vhda/verilog_systemverilog.vim#116]
Expected:
module tst(a,b);
input a;
output b;
endmodule

Actually:
module tst(a,b);
____input a;
____output b;
endmodule
____ it means four spaces.

**Comment by vhda** [comment]
Hi @luoyanghero,

You should be able to use the following configuration to disable that indentation:

``` Vim
let g:verilog_disable_indent_lst = "module"
```

Or using the command:

``` Vim
:VerilogDisableIndentAdd module
```

For more information check the following help pages:

``` Vim
:help :VerilogDisableIndentAdd
:help g:verilog_disable_indent_lst
```

The complete help text for this addon is available as following:

``` Vim
:help verilog_systemverilog.txt
```

**Comment by vhda** [comment]
Assuming fixed.
