### ISSUE TITLE
weird indenting with export

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#120]
```
package automatic regmodel_dpi_pkg;

    export "DPI-SC" task check_reg;

        task check_reg(string mystring, output bit [63:0] o1);

        endtask

endpackage
```

indents incorrectly

**Comment by lewis6991** [comment]
It is indenting like this because of `task` in line 2. To fix this tasks will need to be dequalified when `export` precedes them.

**Comment by vhda** [comment]
Sorry for the time I took to fix this @NicoLugil.
Please review and warn me if there any unexpected consequence to this change.
