### ISSUE TITLE
open .cpp file cannot delete fold

### ISSUE THREAD

**Issue by luoyanghero** [vhda/verilog_systemverilog.vim#125]
When I open .cpp file, it default fold. I go to the folded line and hit space, only unfold one fold block.
How to make it default unfold when open .cpp file?
Or how to unfold all folded line?

**Comment by luoyanghero** [comment]
I select all line(gg, shift+v, G), and hit zO, is it the easiest way?

**Comment by lewis6991** [comment]
zR is the easiest way I think

**Comment by vhda** [comment]
``` vim
autocmd FileType cpp setlocal foldlevel=999
```

You might want to take a look at `:help 'foldlevel'`.

**Comment by vhda** [comment]
Assuming fixed.
