### ISSUE TITLE
pure virtual functions indent wrong

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#14]
This does not indent correctly:

```
virtual class base;

    pure virtual function void a(input int unsigned N, ref t Data);
        pure virtual function void b(input int unsigned N, ref t Data);
            pure virtual function void c(input int unsigned N, ref t Data);

            endclass;
```

**Comment by vhda** [comment]
Please try now.

**Comment by NicoLugil** [comment]
I dont know if this is new or was already like that but it seems all extern and pure virtual functions are now no longer indented in their class:

```
virtual class base;

extern function void x(input int unsigned N, ref t Data);
extern function void y(input int unsigned N, ref t Data);

pure virtual function void a(input int unsigned N, ref t Data);
pure virtual function void b(input int unsigned N, ref t Data);
pure virtual function void c(input int unsigned N, ref t Data);

endclass;
```

**Comment by vhda** [comment]
I screwed up in the last fix. Sorry about that.

**Comment by vhda** [comment]
If you have any problems updating the plugin please reinstall it. Sorry about that.

**Comment by NicoLugil** [comment]
I can not try right now, but would there be a particular reason for that?
So far I have always just downloaded and extracted the zip.

**Comment by vhda** [comment]
I was assuming that you were using a plugin manager like Vundle or Pathogen. But in your case there is no problem.

**Comment by vhda** [comment]
BTW, I hope this issue is now fixed. Could you please confirm?

**Comment by NicoLugil** [comment]
Yes this works fine! Thanks!
