### ISSUE TITLE
Semaphore and Mailbox are not highlighted

### ISSUE THREAD

**Issue by antoinemadec** [vhda/verilog_systemverilog.vim#142]
Hi,

Would it be possible to add 'semaphore' and 'mailbox' in syntax/verilog_systemverilog.vim ?
Those should be treated like 'event' as they are interprocess communication keywords as well.

Excellent pluging by the way :)
Thanks in advance !

**Comment by vhda** [comment]
Fixed in 666d4725310ca09370ae9ebc6a8b9e8325da097b.
But note that there is no special highlight for event like keywords.
If you find something strange please warn me.
