### ISSUE TITLE
Event trigger indentation issue

### ISSUE THREAD

**Issue by antoinemadec** [vhda/verilog_systemverilog.vim#143]
Hi,

I noticed the following behavior when triggerring an event:
```
  initial
  begin
      ->e;  // indented one time too many
  end
```

Here is the diff in indent/verilog_systemverilog.vim I used to fix it:
```
-let s:vlog_open_statement = '\(\<or\>\|[<>:!=?&|^%/*+-]\)'
+let s:vlog_open_statement = '\(\<or\>\|[<>:!=?&|^%/*+]\|-[^>]\)'
```

I tried to run the tests and it seems OK.
I hope this is correct. Could you please push it ?

Thanks again for the swell plugin,
Antoine

**Comment by vhda** [comment]
Check the commit message format I'm using and create a Pull Request, please.
If you have a fix, we can at least have your name on that commit :)

**Comment by antoinemadec** [comment]
My bad, will do ;)

**Comment by vhda** [comment]
Thanks for your contribution Antoine.
