### ISSUE TITLE
'this' and 'null' highlighting

### ISSUE THREAD

**Issue by antoinemadec** [vhda/verilog_systemverilog.vim#145]
Hi,

Here is an example of the issue with 'this', but the same behavior is true for 'null' as well:
```
  foo(this);  // 'this' is highlighted
  a = foo(this); // 'this' is not highlighted anymore
```

Would it be possible to change this behavior so 'this' and 'null' are always highlighted ?
Also, since both are "pointers", would it be possible to put them in the 'verilogObject' group like 'super' (which is also a "pointer") ?

Cheers,
Antoine

**Comment by vhda** [comment]
Could you please try again?

**Comment by antoinemadec** [comment]
The highlighting of 'this' and 'null' is working fine now, thanks a lot!

However 'this' and 'null' are still verilogStatement, could it be possible to change it to verilogObject ?
If not, no problem, I don't wanna sound nitpicky. Thanks again :)

**Comment by vhda** [comment]
That makes sense.
I've been mostly focused on RTL in the last few years, so it's difficult for me to detect this type of inconsistencies.
Keep them coming!

**Comment by vhda** [comment]
I've just noticed I did not read your original issue completely and apologise for that.

**Comment by antoinemadec** [comment]
No problem, thanks a lot for the commit, it works like a charm now.
Cheers!
