### ISSUE TITLE
Left-over g:verilog_disable_indent

### ISSUE THREAD

**Issue by jrudess** [vhda/verilog_systemverilog.vim#165]
In [plugin/verilog_systemverilog.vim](https://github.com/vhda/verilog_systemverilog.vim/blob/9626ac2f6ab5546a4bfcf604af31f1e59be3922e/plugin/verilog_systemverilog.vim#L2), there is a left-over reference to g:verilog_disable_indent.  My assumption is this should be changed to g:verilog_disable_indent_lst or removed.

**Comment by vhda** [comment]
Thanks a bunch @jrudess, I have my personal settings in vimrc, so I completely overlooked that!
