### ISSUE TITLE
indentation with single line if

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#17]
The following if without begin/end stays indented for more than 1 line:

function void sink_driver::build_phase(uvm_phase phase);
    if (!uvm_config_db #(sink_agent_config)::get(this, "", "sink_agent_config", m_cfg) )
        `uvm_fatal("CONFIG_LOAD", "Cannot get() configuration sink_agent_config from uvm_config_db. Have you set() it?")
        // OK to do this herE>
        foreach(rand_bool_gen[ch]) begin
            rand_bool_gen[ch]=new();
        end
    endfunction

**Comment by vhda** [comment]
Should work properly now.

**Comment by NicoLugil** [comment]
Thanks works great!
