### ISSUE TITLE
ALE 

### ISSUE THREAD

**Issue by Luffy4321** [vhda/verilog_systemverilog.vim#172]
when I use ale and verilog_systemverilog，ALE cannot work。but they can work in independently。

**Comment by vhda** [comment]
Have you tried the following:

     let g:ale_linters = {'verilog_systemverilog' : ['verilator'],}

**Comment by vhda** [comment]
Any updates?

**Comment by vhda** [comment]
I've recently delved into ALE and can confirm that Linters are working out of the box in verilog_systemverilog.
