### ISSUE TITLE
Can add highlight for UVM?

### ISSUE THREAD

**Issue by kdurant** [vhda/verilog_systemverilog.vim#177]
I hope to add this feature if possible.

Thanks for your job!

**Comment by vhda** [comment]
At the moment I'm not working in UVM, so I'm not the right person to work on that.
Could I kindly ask you to checkout `:help g:verilog_syntax_custom` and use this to add the necessary support for UVM? If possible, share the final solution so that I can include it in the plugin.
Thanks!

**Comment by vhda** [comment]
Sorry for not being more helpful this time.
