### ISSUE TITLE
Line comment with a comma highlight as code

### ISSUE THREAD

**Issue by toastedcornflakes** [vhda/verilog_systemverilog.vim#183]
Hello! 

The following snippet gets the wrong colour after the comma, as if the line-comment was ended by the comma.

```
assign mysig = condition ?
                // Comment, with comma
                a : b;
```

![comment_vim](https://user-images.githubusercontent.com/6625812/58698603-7356a480-8393-11e9-936e-47e2ccaec7f8.PNG)

How can I debug this further?
Many thanks

**Comment by vhda** [comment]
I had a commit laying around that apparently fixes this.
Would you be so kind a confirm that this is fixed?

**Comment by toastedcornflakes** [comment]
Brilliant, it's indeed fixed. Many thanks, and sorry for the late reply, I somehow missed the notification. Thanks again!
