### ISSUE TITLE
the keyword endmodule is not highlight

### ISSUE THREAD

**Issue by puxiancheng** [vhda/verilog_systemverilog.vim#187]
when i open a .v file though vim, i type G go to the end of the file, the keyword endmodule is not highlight.
if i type ctrl+f go to the end of the file, the keyword endmodule is highlight.

**Comment by vhda** [comment]
Hi @puxiancheng,

Please try adding the following to your vimrc:
```vim
autocmd FileType verilog_systemverilog syntax sync fromstart
```
This will make vim always defines syntax by parsing the complete file. Unfortunately, I expect that this will make the syntax parsing slower because it has to parse more items. But test to see if it becomes too slow or not.

**Comment by puxiancheng** [comment]
thanks!!!
it works, and it does not become too slow.
