### ISSUE TITLE
remove g:tagbar_type_verilog_systemverilog

### ISSUE THREAD

**Issue by antoinemadec** [vhda/verilog_systemverilog.vim#188]
The definition of **g:tagbar_type_verilog_systemverilog** overrides user's definition of it.
Would it be possible to remove it?

In my case, I don't want to use the universal Ctags, the exuberant Ctags are enough for me.
However, since _verilog_systemveriog_ overrides **g:tagbar_type_verilog_systemverilog**, I cannot use _tagbar_.

I think this should be added in the doc (which it is on _tagbar_ Wiki), not in the plugin it self.
What do you think?

**Comment by vhda** [comment]
Hi @antoinemadec I keep forgetting to take care of this, sorry. Will try to do it tomorrow.

**Comment by vhda** [comment]
Please check Pull Request #189

**Comment by vhda** [comment]
Fixed in #189
