### ISSUE TITLE
issue with syntax hilight with inline/multi-line comments

### ISSUE THREAD

**Issue by justrajdeep** [vhda/verilog_systemverilog.vim#193]
Hi 

This plugin is amazing. I cannot thank you enough.

I see only a trivial issue with syntax highlight.

    /* uvm_analysis_port #(REQ) mon_analysis_port;  //TLM analysis port */

if i have something like the above line; it misses the multi line comment closure(`*/`) because of the inline comment(`//`).

Can you please take look?

**Comment by kirsa** [comment]
Also seeing this issue. Would really appreciate any pointers on how to resolve this.

**Comment by kirsa** [comment]
My local fix for this is in ~/.vim/bundle/verilog_systemverilog.vim/syntax/verilog_systemverilog.vim add the following after line 357 :
syn region verilogComment start="/\*" end="/*\"

**Comment by vhda** [comment]
Could you please try again?

**Comment by kirsa** [comment]
Works for me, thanks!
