### ISSUE TITLE
virtual functions indent

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#20]
This code indents incorrectly: 

class x;
    virtual function void pack(ref bit[W-1:0] out);
    $display("hi");
endfunction
function void y();
endfunction
endclass

when removing the virtual keyword it is ok.

**Comment by vhda** [comment]
Try now.

**Comment by NicoLugil** [comment]
Perfect! What a quick fix :+1:

**Comment by vhda** [comment]
If you look at the diff you can see it was pretty straight forwards ;)
Keep them coming!
