### ISSUE TITLE
Verilator error format changed.

### ISSUE THREAD

**Issue by prwang** [vhda/verilog_systemverilog.vim#201]
The default error format does not work for verilator version 4.106 (from MSYS2 repository).  Now the error string contains an column number :
`%Error: example.v:32:27: syntax error, unexpected or, expecting ',' or ';'`
So the column must be matched
 `CompilerSet errorformat=%%%trror%.%#:\ %f:%l:%c:\ %m`
 or the vim will try to open a file called `example.v:32` which does not exist at all.

**Comment by vhda** [comment]
Hi @prwang,
Could you please confirm if the merged commit resolves this issue?
Thanks!
