### ISSUE TITLE
Not working in version 8.2

### ISSUE THREAD

**Issue by kiranreddi** [vhda/verilog_systemverilog.vim#221]
Hi, it was working fine till I moved to the latest vim version 8.2. After moving to this version syntax stopped working. Any info if we have to do anything more to make it work? 

thanks

**Comment by vhda** [comment]
Hi @kiranreddi,
I've been using it successfully with Vim 9, so either this was a temporary bug in Vim, or something else changed.

**Comment by vhda** [comment]
Closing due to no updates. Please feel free to re-open if problem is still not solved.
