### ISSUE TITLE
Not working in Neovim 0.8.1

### ISSUE THREAD

**Issue by yosemitescott** [vhda/verilog_systemverilog.vim#222]
Hi,

After updating from neovim 0.7.2 to 0.8.1 and using the same configuration setup, the various formatting ability seems to be disabled.  

In 0.7.2, if I let g:verilog_verbose = 1, I get a lot of various messages as things are formatted as expected.

When I do the same in 0.8.1, there are no messages at all but there is also no formatting

I did notice that my svls language server is now working with 0.8.1 where it wasn't fully working with 0.7.2... could there be a conflict between the two? I did disable svls and didn't see a difference.

**Comment by vhda** [comment]
I'm still on normal Vim, so it will be hard to support you on this.
I recommend that you temporarily disable all plugins except this one and see if this makes any change.

**Comment by yosemitescott** [comment]
Thanks vhda for the response... I did some more investigation and before this last update, neovim has the filetype of a SV file as "verilog_systemverilog" whereas now, the filetype is "systemverilog".  In 0.8.1, if I manually set the filetype to verilog_systemverilog, the formatting of this plugs works again but I don't know if other things don't work if the filetype is just "systemverilog".  Does this plugin rely on the filetype "verilog_systemverilog" and if so, is there a way to tell it to also treat "systemverilog" as the same?

**Comment by yosemitescott** [comment]
My googlefu led me to a workaround so leaving this here:

Issue identified here:  https://github.com/neovim/neovim/issues/19008#issuecomment-1293515191
Workaround here: https://github.com/antoinemadec/dotfiles/commit/67a127d1df4fa2398c89e7cc300810441565a1c3

**Comment by vhda** [comment]
Thanks for updating the issue with information that can help others in the future.
