### ISSUE TITLE
OmniComplete doesn't work

### ISSUE THREAD

**Issue by lewis6991** [vhda/verilog_systemverilog.vim#23]
Looks to me like there a syntax error in the omni complete function. When I try to use omni, vim gives me the following error:

```
Error detected while processing function verilog_systemverilog#Complete:
line 119:
E583: multiple :else:   else
```

File used on:

``` systemverilog
class b;
   bit field1;
   bit field2;
endclass : b

class a;
    b b_inst;

    function void update();
        b_inst.[omni complete here]
    endfunction : update
endclass : a
```

**Comment by vhda** [comment]
I've just pushed the fix in https://github.com/vhda/verilog_systemverilog.vim/commit/600a102b05e53091462926874c9559014657d7bc, which was laying around in my work repository.

Please confirm if it fixes your issue.

**Comment by lewis6991** [comment]
I made the same change myself and confirm does work.

**Comment by vhda** [comment]
Perfect!
I am aware that omni-completion still has some limitations, so feel free to submit enhancement requests for features you would find important.
Pull Requests are also welcome :)
