### ISSUE TITLE
How to install it manually?

### ISSUE THREAD

**Issue by No-drink** [vhda/verilog_systemverilog.vim#244]
Hi, as I’m using our company’s server, I cannot install Git or access the internet. Hence, I can only install it manually. I have tried several methods to install it, including using runtimepath and copying the subdirectory into .vim, but all these methods have failed.

Could you please let me know how to install it without a plugin manager? My Vim version is 7.4.629. Thank you very much, and I apologize for the inconvenience.

**Comment by weigian** [comment]
you may try git install in your local and then upload the .vim directory to server.

**Comment by No-drink** [comment]
Oh yes... This is a feasible solution. Thank you very much!
