### ISSUE TITLE
How do you enable and view the verbose logging?

### ISSUE THREAD

**Issue by lewis6991** [vhda/verilog_systemverilog.vim#25]
I'm trying to enable the verbose logging for the omni-completion script. Could someone tell me the flow for doing this? I'm fairly new to vimscript so assume I know nothing.

Thanks

**Comment by vhda** [comment]
Verbose "logging" is enabled with `:let b:verilog_omni_verbose`.
The messages are printed through `echom` command, which means that they are not displayed directly in the screen. To view the messages run `:messages`.

Check `:help :echom` and `:help :messages` for more information.

**Comment by lewis6991** [comment]
Thanks
