### ISSUE TITLE
Folding does not work for nested classes

### ISSUE THREAD

**Issue by lewis6991** [vhda/verilog_systemverilog.vim#29]
The following does not work:

``` systemverilog
class a;
    class b;
        //...
    endclass
endclass
```

Any idea on how this can be fixed?

**Comment by vhda** [comment]
The "block" syntax folding supports nested folding.
From what I can see (because I no longer remembered) it should be just a matter of removing the `keepend` option from the "class" folding.

**Comment by vhda** [comment]
Fixed in https://github.com/vhda/verilog_systemverilog.vim/commit/90c9ba8df568b00c6e98c0370a11fa4648f304b7
