### ISSUE TITLE
commens containing the 'if' keyword give wrong indentation

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#3]
If a comment line contains the 'if' keyword the next line of comments is indented:

// if there is...
     // more comments

**Comment by vhda** [comment]
This behavior should have been corrected by bf98d8b76ac18b10b8d88715d7937746b853509a.

**Comment by vhda** [comment]
This behavior should have been corrected by eb9a9b49b2f8eb50eed5172d57a93ad543190539.

**Comment by NicoLugil** [comment]
Thanks! Works fine now.
