### ISSUE TITLE
fork join indenting

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#5]
fork - join with named begin/end block indenting seems to be broken:

```
task run_phase(uvm_phase phase);

    fork 
    begin : isolating_thread
        do_something();
    end : isolating_thread 
join

endtask
```

**Comment by NicoLugil** [comment]
Does not seem to be related to the naming of the block. E.g. following stuff also indents weird:

```
    fork 
    begin
    do_something();
end 
join
```

```
    fork begin
        do_something();
    end
join
```

**Comment by vhda** [comment]
I've identified the location where this happens, but I need to understand what was its full purpose to guarantee that I do not regress something.
I'm also starting to think that best solution would be to re-write the indentation script from scratch...

**Comment by vhda** [comment]
Out of curiosity, would you mind testing this [addon](http://vim.sourceforge.net/scripts/script.php?script_id=4743) and see if the indent works better?
At the moment I am not working with SV, so it's more difficult for me to test it myself.

**Comment by NicoLugil** [comment]
Do you mean putting the content of that projects' indent file into this projects indent file, and see what happens? I could give that a brief try tomorrow.

**Comment by vhda** [comment]
I was proposing to completely replace the verilog_systemverilog addon with other one.
But your solution should work as well, as long as you properly rename the file :)
Thanks in advance.

**Comment by NicoLugil** [comment]
I briefly tried it, but it seems to be broken in many places.
Also if you look to the issues of that project, you already see a lot of indent issues.
The indent of this project is I think better quality.

**Comment by vhda** [comment]
Thanks for testing this for me.

**Comment by vhda** [comment]
This specific issue should be fixed.
I still need to review the indentation of functions, which is not perfect at the moment, but the fix will require some fundamental changes to the script.

**Comment by NicoLugil** [comment]
Thanks for the update.

As a minor thing: when there is a space after the begin statement the indenting is not ok, but that is probably another issue.

**Comment by vhda** [comment]
I already found and fixed the white space issue on my local repository.

**Comment by NicoLugil** [comment]
Is this included in the latest release?

**Comment by vhda** [comment]
It was lost in a local branch, but I've just cherry-picked it for you :)
