### ISSUE TITLE
Allow indentation inside class, interface, etc

### ISSUE THREAD

**Issue by vhda** [vhda/verilog_systemverilog.vim#55]
The option `b:verilog_indent_modules` allows having the code indented inside modules, but there is no such option for class, interface, etc. There should exist a new option that allows this, preferably something that allows configuration of which elements to indent, like is done with `g:verilog_syntax_fold`.

**Comment by lewis6991** [comment]
Added in a9dac32a2df51cdc2912f0bde48f8fe65090548f
