### ISSUE TITLE
generic interface reference doesnt indent correctly

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#69]
```
module dut_wrapper (
    interface source_IF,
        interface sink_IF,
            interface ctrl_IF,
```

**Comment by lewis6991** [comment]
I've completely overlooked this. Good catch! The script is probably seeing the keyword `interface` and indenting from that.

**Comment by vhda** [comment]
Fixed in #74

**Comment by lewis6991** [comment]
@NicoLugil would you be able to verify this fix for us? You just need to update to the newest version.

**Comment by NicoLugil** [comment]
Yes this works fine now! Thanks!
