### ISSUE TITLE
indent after 2 asserts

### ISSUE THREAD

**Issue by NicoLugil** [vhda/verilog_systemverilog.vim#7]
this code: 

```
task run_phase(uvm_phase phase);

    assert(out>0) else $warning("xxx");
    assert(out>0) else $warning("xxx");
foreach(out[i]) begin
    out[i]=new;
end


endtask
```

doesn't indent correctly.

With a single assert it does indent correctly

**Comment by vhda** [comment]
Hi Nico,
Apparently my previous fix was not good enough. Give me more time to look into this.
Thanks.

**Comment by vhda** [comment]
Indenting of assertions should now be correctly implemented.

**Comment by NicoLugil** [comment]
Thanks for the fix!
